/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package practico_5_grupo14;

import javax.swing.JOptionPane;

/**
 *
 * @author Leandro Naranjo
 */
public class AgregarCiudades extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarCiudades
     */
    public AgregarCiudades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textCiudad = new javax.swing.JTextField();
        btnGuardarCiudad = new javax.swing.JButton();
        btnSalirAggCiudad = new javax.swing.JButton();

        setTitle("Agregar Ciudades");

        jLabel1.setFont(new java.awt.Font("Dubai", 0, 22)); // NOI18N
        jLabel1.setText("Agregar Ciudad");

        jLabel2.setText("Nombre Ciudad");

        btnGuardarCiudad.setText("Guardar");
        btnGuardarCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarCiudadMouseClicked(evt);
            }
        });
        btnGuardarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCiudadActionPerformed(evt);
            }
        });

        btnSalirAggCiudad.setText("Salir");
        btnSalirAggCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirAggCiudadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnGuardarCiudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalirAggCiudad)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(textCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCiudad)
                    .addComponent(btnSalirAggCiudad))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCiudadActionPerformed

    private void btnGuardarCiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarCiudadMouseClicked
        // TODO add your handling code here:
        if (textCiudad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el nombre de la ciudad", "Campo vacio", JOptionPane.WARNING_MESSAGE);
        } else {
            if (Telefonica.ciudades.contains(textCiudad.getText())) {
                JOptionPane.showMessageDialog(this, "La ciudad '" + textCiudad.getText() + "' ya existe en el listado", "Ciudad existente", JOptionPane.WARNING_MESSAGE);
                textCiudad.setText("");
                textCiudad.requestFocus();
            } else {
                Telefonica.ciudades.add(textCiudad.getText());
                JOptionPane.showMessageDialog(this, "Ciudad '" + textCiudad.getText() + "' agregada exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE);

            }
            textCiudad.setText(" ");
            textCiudad.requestFocus();
        }
    }//GEN-LAST:event_btnGuardarCiudadMouseClicked

    private void btnSalirAggCiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirAggCiudadMouseClicked
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_btnSalirAggCiudadMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCiudad;
    private javax.swing.JButton btnSalirAggCiudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textCiudad;
    // End of variables declaration//GEN-END:variables
}
