/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package practico_5_grupo14;

import clases.Contacto;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro Naranjo
 */
public class BuscarPorCiudad extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarPorCiudad
     */
    private DefaultTableModel modelo;

    public BuscarPorCiudad() {
        initComponents();
        cargaBoxCiudades();
        initTabla();
    }

    private void initTabla() {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modelo.addColumn("DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Dirección");
        modelo.addColumn("Teléfono");

        tablaBuscarCiudades.setModel(modelo);
    }

    private void cargaBoxCiudades() {
        DefaultComboBoxModel<String> ciudades = new DefaultComboBoxModel<>();
        ciudades.addElement("Seleccionar una ciudad");
        if (Telefonica.ciudades.isEmpty()) {
            ciudades.addElement("No hay ciudades cargadas");
        } else {
            for (String c : Telefonica.ciudades) {
                ciudades.addElement(c);

            }
        }
        comboCiudad.setModel(ciudades);

        comboCiudad.addItemListener(new java.awt.event.ItemListener() {
            @Override
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCiudadItemStateChanged(evt);
            }
        });
    }

    private void comboCiudadItemStateChanged(java.awt.event.ItemEvent evt) {
        // solo procesar cuando el item es seleccionado (no deseleccionado)
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String ciudadSeleccionada = (String) evt.getItem();

            // validar que sea una ciudad valida
            if (ciudadSeleccionada != null
                    && !ciudadSeleccionada.equals("Seleccionar una ciudad")
                    && !ciudadSeleccionada.equals("No hay ciudades cargadas")) {

                // cargar la tabla con los contactos de la ciudad seleccionada
                cargarTablaContactos(ciudadSeleccionada);
            } else {
                // limpiar la tabla si se selecciona un placeholder
                modelo.setRowCount(0);
            }
        }
    }

    private void cargarTablaContactos(String ciudad) {
        // limpiar la tabla antes de cargar nuevos datos
        modelo.setRowCount(0);

        // recorrer todos los contactos del directorio
        for (Map.Entry<Long, Contacto> entry : Telefonica.d1.getCliente().entrySet()) {
            Contacto contacto = entry.getValue();

            // verificar si el contacto pertenece a la ciudad seleccionada
            if (contacto.getCiudad().equalsIgnoreCase(ciudad)) {
                // Usar model.addRow según la consigna
                modelo.addRow(new Object[]{
                    contacto.getDni(),
                    contacto.getNombre(),
                    contacto.getApellido(),
                    contacto.getDireccion(),
                    entry.getKey() 
                });
            }
        }

       
        int cantidad = modelo.getRowCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboCiudad = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBuscarCiudades = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnSalirBuscarPorCiudad = new javax.swing.JButton();

        setTitle("Buscar por Ciudad");

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel1.setText("Buscar Clientes por Ciudad");
        jLabel1.setToolTipText("");

        tablaBuscarCiudades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaBuscarCiudades);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ciudades:");

        btnSalirBuscarPorCiudad.setText("Salir");
        btnSalirBuscarPorCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirBuscarPorCiudadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalirBuscarPorCiudad)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(220, 220, 220))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSalirBuscarPorCiudad)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirBuscarPorCiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirBuscarPorCiudadMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirBuscarPorCiudadMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirBuscarPorCiudad;
    private javax.swing.JComboBox<String> comboCiudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaBuscarCiudades;
    // End of variables declaration//GEN-END:variables
}
