/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practico_5_grupo14;

import clases.*;
import java.util.ArrayList;

/**
 *
 * @author Leandro Naranjo
 */
public class Telefonica extends javax.swing.JFrame {

    public static DirectorioTelefonico d1 = new DirectorioTelefonico();
    public static ArrayList<String> ciudades = new ArrayList();

    /**
     * Creates new form Telefonica
     */
    public Telefonica() {
        initComponents();
        initCiudades();
        cargaDatos();

    }

    public void initCiudades() {
        ciudades.add("San Luis");
        ciudades.add("Córdoba");
        ciudades.add("Mendoza");
        ciudades.add("Rosario");
        ciudades.add("Santa Fe");
    }

    public void cargaDatos() {
        //Agregar Contactos A)
        Contacto c1 = new Contacto(45563392, "Candela", "Naranjo", "San Luis", "Caseros 1213");
        d1.agregarContacto(2664863827L, c1);

        Contacto c2 = new Contacto(25811214, "Maria", "Sosa", "San Luis", "Corrientes 12");
        d1.agregarContacto(2664320797L, c2);

        Contacto c3 = new Contacto(45968325, "Lucas", "Quevedo", "Cordoba", "San Martin 1234");
        d1.agregarContacto(2647856974L, c3);

        Contacto c4 = new Contacto(26985741, "Laura", "Diaz", "Mendoza", "Constitucion 191");
        d1.agregarContacto(2657987541L, c4);

        //Buscar Contacto por telefono B)
        Contacto contactoEncontrado = d1.buscarContacto(2664863827L);
        if (contactoEncontrado != null) {
            System.out.println("Contacto encontrado: " + contactoEncontrado.getNombre() + " "
                    + contactoEncontrado.getApellido() + " - " + contactoEncontrado.getCiudad());
        } else {
            System.out.println("Contacto no encontrado");
        }

        /*Esta parte no funciona si los metodos no estan en funcionamiento
        //Buscar Contacto por Apellido C)
        Set<Long> telefonosPerez = d1.buscarTelefono("Perez");
        System.out.println("Teléfonos encontrados: " + telefonosPerez);

        //Buscar Contacto por Ciudad D)
        ArrayList<Contacto> contactosSanLuis = d1.buscarContactos("San Luis");
        System.out.println("Contactos en Córdoba: " + contactosSanLuis.size());
        for (Object contacto : contactosSanLuis) {
            System.out.println("Contacto: " + contacto.toString());
        }

        //Borrar Contacto E)
        d1.borrarContacto(2664320797L);
        System.out.println("Contacto borrado. Verificando...");
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mItemAgregarCliente = new javax.swing.JMenuItem();
        mItemBuscarCliente = new javax.swing.JMenuItem();
        mItemBorrarCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mItemBuscarClienteCiudad = new javax.swing.JMenuItem();
        mItemBuscarClienteApellido = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnAgregarCiudad = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        jMenu1.setText("Clientes");

        mItemAgregarCliente.setText("Agregar Cliente");
        mItemAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mItemAgregarClienteMouseClicked(evt);
            }
        });
        mItemAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAgregarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mItemAgregarCliente);

        mItemBuscarCliente.setText("Buscar Cliente");
        mItemBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemBuscarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mItemBuscarCliente);

        mItemBorrarCliente.setText("Borrar Cliente");
        mItemBorrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mItemBorrarClienteMouseClicked(evt);
            }
        });
        mItemBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemBorrarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mItemBorrarCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Directorio");

        mItemBuscarClienteCiudad.setText("Buscar Clientes por Ciudad");
        mItemBuscarClienteCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mItemBuscarClienteCiudadMouseClicked(evt);
            }
        });
        mItemBuscarClienteCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemBuscarClienteCiudadActionPerformed(evt);
            }
        });
        jMenu2.add(mItemBuscarClienteCiudad);

        mItemBuscarClienteApellido.setText("Buscar Telefono por Apellido");
        mItemBuscarClienteApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemBuscarClienteApellidoActionPerformed(evt);
            }
        });
        jMenu2.add(mItemBuscarClienteApellido);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ciudades");

        btnAgregarCiudad.setText("Agregar Ciudad");
        btnAgregarCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarCiudadMouseClicked(evt);
            }
        });
        btnAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCiudadActionPerformed(evt);
            }
        });
        jMenu3.add(btnAgregarCiudad);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Salir");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mItemAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAgregarClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AgregarCliente ac = new AgregarCliente();
        ac.setLocation((escritorio.getWidth() - ac.getWidth()) / 2, (escritorio.getHeight() - ac.getHeight()) / 2);
        ac.setVisible(true);
        escritorio.add(ac);
        ac.toFront();


    }//GEN-LAST:event_mItemAgregarClienteActionPerformed

    private void mItemBuscarClienteApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemBuscarClienteApellidoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BuscarPorApellido busqueda=new BuscarPorApellido();
        busqueda.setLocation((escritorio.getWidth() - busqueda.getWidth()) / 2, (escritorio.getHeight() - busqueda.getHeight()) / 2);
        busqueda.setVisible(true);
        escritorio.add(busqueda);
        busqueda.toFront();
    }//GEN-LAST:event_mItemBuscarClienteApellidoActionPerformed

    private void btnAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCiudadActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AgregarCiudades aggC = new AgregarCiudades();
        aggC.setLocation((escritorio.getWidth() - aggC.getWidth()) / 2, (escritorio.getHeight() - aggC.getHeight()) / 2);
        aggC.setVisible(true);
        escritorio.add(aggC);
        aggC.toFront();
    }//GEN-LAST:event_btnAgregarCiudadActionPerformed

    private void mItemBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemBorrarClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        borrarCliente bc = new borrarCliente();
        bc.setLocation((escritorio.getWidth() - bc.getWidth()) / 2, (escritorio.getHeight() - bc.getHeight()) / 2);

        bc.setVisible(true);
        escritorio.add(bc);
        bc.toFront();

    }//GEN-LAST:event_mItemBorrarClienteActionPerformed

    private void mItemAgregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mItemAgregarClienteMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_mItemAgregarClienteMouseClicked

    private void mItemBorrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mItemBorrarClienteMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_mItemBorrarClienteMouseClicked

    private void btnAgregarCiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCiudadMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAgregarCiudadMouseClicked

    private void mItemBuscarClienteCiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mItemBuscarClienteCiudadMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mItemBuscarClienteCiudadMouseClicked

    private void mItemBuscarClienteCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemBuscarClienteCiudadActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BuscarPorCiudad busqueda=new BuscarPorCiudad();
        busqueda.setLocation((escritorio.getWidth() - busqueda.getWidth()) / 2, (escritorio.getHeight() - busqueda.getHeight()) / 2);
        busqueda.setVisible(true);
        escritorio.add(busqueda);
        busqueda.toFront();
    }//GEN-LAST:event_mItemBuscarClienteCiudadActionPerformed

    private void mItemBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemBuscarClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BuscarCliente busqueda=new BuscarCliente();
        busqueda.setLocation((escritorio.getWidth() - busqueda.getWidth()) / 2, (escritorio.getHeight() - busqueda.getHeight()) / 2);
        busqueda.setVisible(true);
        escritorio.add(busqueda);
        busqueda.toFront();
    }//GEN-LAST:event_mItemBuscarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telefonica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telefonica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telefonica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telefonica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telefonica().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAgregarCiudad;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mItemAgregarCliente;
    private javax.swing.JMenuItem mItemBorrarCliente;
    private javax.swing.JMenuItem mItemBuscarCliente;
    private javax.swing.JMenuItem mItemBuscarClienteApellido;
    private javax.swing.JMenuItem mItemBuscarClienteCiudad;
    // End of variables declaration//GEN-END:variables
}
